In [2]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)


1.18.1


In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))
#4. Print a.
a

array([[[0.20146041, 0.90956068, 0.35340909, 0.77014875, 0.7402752 ],
        [0.6043516 , 0.01538098, 0.88123792, 0.26373677, 0.34678654],
        [0.9965471 , 0.07041536, 0.23711921, 0.9029004 , 0.24972986]],

       [[0.52438375, 0.59946162, 0.80136286, 0.15735357, 0.88622234],
        [0.93327638, 0.3496869 , 0.76452743, 0.81689607, 0.37324134],
        [0.73817387, 0.26401738, 0.04850065, 0.81974282, 0.56688678]]])

In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
bp = np.random.random((5,2,3))
b = np.full_like(bp,1)


#6. Print b
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?
np.array_equal(a,b)
# esta funcion de python compara la forma de dos arrays y devuelve un booleano

False

In [7]:
#8. Are you able to add a and b? Why or why not?
sum(a,b)
# no ya que el tamaño de los valores en el shape de las matrices tienen que ser iguales para poder ser sumadas

ValueError: operands could not be broadcast together with shapes (5,2,3) (3,5) 

In [8]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b,(1,2,0))
c.shape

(2, 3, 5)

In [9]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = sum(a,c)
d
# porque los valores dentro de las matrices estan organizadas de la misma forma

array([[[1.72584416, 2.5090223 , 2.15477195, 1.92750232, 2.62649754],
        [2.53762798, 1.36506788, 2.64576536, 2.08063283, 1.72002788],
        [2.73472097, 1.33443274, 1.28561986, 2.72264322, 1.81661663]],

       [[1.72584416, 2.5090223 , 2.15477195, 1.92750232, 2.62649754],
        [2.53762798, 1.36506788, 2.64576536, 2.08063283, 1.72002788],
        [2.73472097, 1.33443274, 1.28561986, 2.72264322, 1.81661663]]])

In [10]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print("-"*100)
print(d)
# el valor de e es la suma de las matrices de a y c

[[[0.20146041 0.90956068 0.35340909 0.77014875 0.7402752 ]
  [0.6043516  0.01538098 0.88123792 0.26373677 0.34678654]
  [0.9965471  0.07041536 0.23711921 0.9029004  0.24972986]]

 [[0.52438375 0.59946162 0.80136286 0.15735357 0.88622234]
  [0.93327638 0.3496869  0.76452743 0.81689607 0.37324134]
  [0.73817387 0.26401738 0.04850065 0.81974282 0.56688678]]]
----------------------------------------------------------------------------------------------------
[[[1.72584416 2.5090223  2.15477195 1.92750232 2.62649754]
  [2.53762798 1.36506788 2.64576536 2.08063283 1.72002788]
  [2.73472097 1.33443274 1.28561986 2.72264322 1.81661663]]

 [[1.72584416 2.5090223  2.15477195 1.92750232 2.62649754]
  [2.53762798 1.36506788 2.64576536 2.08063283 1.72002788]
  [2.73472097 1.33443274 1.28561986 2.72264322 1.81661663]]]


In [11]:
#12. Multiply a and c. Assign the result to e.
e = a * c
e

array([[[0.20146041, 0.90956068, 0.35340909, 0.77014875, 0.7402752 ],
        [0.6043516 , 0.01538098, 0.88123792, 0.26373677, 0.34678654],
        [0.9965471 , 0.07041536, 0.23711921, 0.9029004 , 0.24972986]],

       [[0.52438375, 0.59946162, 0.80136286, 0.15735357, 0.88622234],
        [0.93327638, 0.3496869 , 0.76452743, 0.81689607, 0.37324134],
        [0.73817387, 0.26401738, 0.04850065, 0.81974282, 0.56688678]]])

In [12]:
#13. Does e equal to a? Why or why not?
print(e)
print("-"*100)
print(a)
np.array_equal(a,e)
# son iguales ya que la multiplicacion de los valores en la matriz 
# a multiplicados por los valores 1 de la matriz c dan el mismo resultado

[[[0.20146041 0.90956068 0.35340909 0.77014875 0.7402752 ]
  [0.6043516  0.01538098 0.88123792 0.26373677 0.34678654]
  [0.9965471  0.07041536 0.23711921 0.9029004  0.24972986]]

 [[0.52438375 0.59946162 0.80136286 0.15735357 0.88622234]
  [0.93327638 0.3496869  0.76452743 0.81689607 0.37324134]
  [0.73817387 0.26401738 0.04850065 0.81974282 0.56688678]]]
----------------------------------------------------------------------------------------------------
[[[0.20146041 0.90956068 0.35340909 0.77014875 0.7402752 ]
  [0.6043516  0.01538098 0.88123792 0.26373677 0.34678654]
  [0.9965471  0.07041536 0.23711921 0.9029004  0.24972986]]

 [[0.52438375 0.59946162 0.80136286 0.15735357 0.88622234]
  [0.93327638 0.3496869  0.76452743 0.81689607 0.37324134]
  [0.73817387 0.26401738 0.04850065 0.81974282 0.56688678]]]


True

In [13]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

2.734720968767415
1.2856198558959973
2.0791195744734834


In [14]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty([2,3,5])
f

array([[[0.20146041, 0.90956068, 0.35340909, 0.77014875, 0.7402752 ],
        [0.6043516 , 0.01538098, 0.88123792, 0.26373677, 0.34678654],
        [0.9965471 , 0.07041536, 0.23711921, 0.9029004 , 0.24972986]],

       [[0.52438375, 0.59946162, 0.80136286, 0.15735357, 0.88622234],
        [0.93327638, 0.3496869 , 0.76452743, 0.81689607, 0.37324134],
        [0.73817387, 0.26401738, 0.04850065, 0.81974282, 0.56688678]]])

In [15]:
print(d)
print("-"*100)
print(f)

[[[1.72584416 2.5090223  2.15477195 1.92750232 2.62649754]
  [2.53762798 1.36506788 2.64576536 2.08063283 1.72002788]
  [2.73472097 1.33443274 1.28561986 2.72264322 1.81661663]]

 [[1.72584416 2.5090223  2.15477195 1.92750232 2.62649754]
  [2.53762798 1.36506788 2.64576536 2.08063283 1.72002788]
  [2.73472097 1.33443274 1.28561986 2.72264322 1.81661663]]]
----------------------------------------------------------------------------------------------------
[[[0.20146041 0.90956068 0.35340909 0.77014875 0.7402752 ]
  [0.6043516  0.01538098 0.88123792 0.26373677 0.34678654]
  [0.9965471  0.07041536 0.23711921 0.9029004  0.24972986]]

 [[0.52438375 0.59946162 0.80136286 0.15735357 0.88622234]
  [0.93327638 0.3496869  0.76452743 0.81689607 0.37324134]
  [0.73817387 0.26401738 0.04850065 0.81974282 0.56688678]]]


In [41]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
# todavia no resuelto
print(f)
print("-"*100)
"""
for lst in range(d.shape[0]):
    for num in range(d.shape[1]):
        for nume in range(d.shape[2]):
            if d[(lst,num,nume)] == d_max:
                f[(lst,num,nume)] = 100
            elif d[(lst,num,nume)] == d_min:
                f[(lst,num,nume)] = 0
            elif d[(lst,num,nume)] == d_mean:
                f[(lst,num,nume)] = 50
            elif d[(lst,num,nume)] > d_min and d[(lst,num,nume)] <  d_mean:
                f[(lst,num,nume)] = 25
            elif d[(lst,num,nume)] < d_max and d[(lst,num,nume)] >  d_mean: 
                f[(lst,num,nume)] = 75


# comparacion y adicion de numpy
#f_copia = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max)
#f_copia


In [42]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(f)

[[[ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]
  [100.  25.   0.  75.  25.]]

 [[ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]
  [100.  25.   0.  75.  25.]]]


In [40]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
#f_copia = 'B' * (d > d_min) * (d < d_mean) + 'D' * (d < d_max) * (d > d_mean) + 'A' * (d == d_min) + 'E' * (d == d_max)
#print('')
# tres vectores determinados por x,y,z
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[(x,y,z)] == d_max:
                f[(x,y,z)]= 'E'
                
            elif d[(x,y,z)] == d_min:
                f[(x,y,z)] = 'A'
                
            elif d[(x,y,z)] == d_mean:
                f[(x,y,z)] = 'C'
                
            elif d[(x,y,z)] > d_min and d[(x,y,z)] <  d_mean:
                f[(x,y,z)] = 'B'
                
            elif d[(x,y,z)] < d_max and d[(x,y,z)] >  d_mean: 
                f[(x,y,z)] = 'D'

ValueError: could not convert string to float: 'B'

In [36]:
d.shape

(2, 3, 5)