#1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [3]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Data Analyst/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Data Analyst/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Data Analyst/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.11

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [12]:
a = np.random.random((2,3,5))

In [13]:
#4. Print a.

In [14]:
a

array([[[0.23127249, 0.15698233, 0.12924646, 0.6509969 , 0.87280378],
        [0.67762028, 0.432092  , 0.98303467, 0.14979228, 0.93655605],
        [0.54608802, 0.82390433, 0.17859995, 0.50910299, 0.51149499]],

       [[0.59377236, 0.15981071, 0.77047189, 0.24514972, 0.99838908],
        [0.33925353, 0.91711089, 0.92909992, 0.54960672, 0.42133838],
        [0.47132709, 0.59547064, 0.89432701, 0.28183695, 0.35473588]]])

In [15]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [18]:
b = np.ones((5,2,3))

In [19]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#7. Do a and b have the same size? How do you prove that in Python code?

In [20]:
print(a.size,  b.size)

30 30


#8. Are you able to add a and b? Why or why not?


No because a and b are not constructed the same way 


#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [22]:
c = np.transpose(b,(1,2,0))

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [24]:
d = a.__add__(c)

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
d
print(a)
print(d)
print('that d is grater than a in aproximately 40-50%')

[[[0.23127249 0.15698233 0.12924646 0.6509969  0.87280378]
  [0.67762028 0.432092   0.98303467 0.14979228 0.93655605]
  [0.54608802 0.82390433 0.17859995 0.50910299 0.51149499]]

 [[0.59377236 0.15981071 0.77047189 0.24514972 0.99838908]
  [0.33925353 0.91711089 0.92909992 0.54960672 0.42133838]
  [0.47132709 0.59547064 0.89432701 0.28183695 0.35473588]]]
[[[1.23127249 1.15698233 1.12924646 1.6509969  1.87280378]
  [1.67762028 1.432092   1.98303467 1.14979228 1.93655605]
  [1.54608802 1.82390433 1.17859995 1.50910299 1.51149499]]

 [[1.59377236 1.15981071 1.77047189 1.24514972 1.99838908]
  [1.33925353 1.91711089 1.92909992 1.54960672 1.42133838]
  [1.47132709 1.59547064 1.89432701 1.28183695 1.35473588]]]
that d is grater than a in aproximately 40-50%


#12. Multiply a and c. Assign the result to e.

In [37]:
e = a*c
e

array([[[0.23127249, 0.15698233, 0.12924646, 0.6509969 , 0.87280378],
        [0.67762028, 0.432092  , 0.98303467, 0.14979228, 0.93655605],
        [0.54608802, 0.82390433, 0.17859995, 0.50910299, 0.51149499]],

       [[0.59377236, 0.15981071, 0.77047189, 0.24514972, 0.99838908],
        [0.33925353, 0.91711089, 0.92909992, 0.54960672, 0.42133838],
        [0.47132709, 0.59547064, 0.89432701, 0.28183695, 0.35473588]]])

#13. Does e equal to a? Why or why not?
Because multiplying a * (aT + U) (unitary matrix) = a


#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [66]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max,d_min,d_mean)

1.9983890775850095 1.1292464582031205 1.5437096098214558


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [93]:
f = np.zeros((2,3,5))
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])


"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [94]:
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] == d_min:
                f[x][y][z] = 0        
            elif d[x][y][z] > d_min and d[x][y][z]<d_mean:
                f[x][y][z] += 25
            elif d[x][y][z] == d_mean:
                f[x][y][z] += 50
            elif d[x][y][z]> d_mean and d[x][y][z]<d_max:
                f[x][y][z] += 75
            elif d[x][y][z] == d_max:
                f[x][y][z] += 100
            
                

In [95]:
f


array([[[ 25.,  25.,   0.,  75.,  75.],
        [ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.]],

       [[ 75.,  25.,  75.,  25., 100.],
        [ 25.,  75.,  75.,  75.,  25.],
        [ 25.,  75.,  75.,  25.,  25.]]])